apiVersion: v1
kind: ConfigMap
metadata:
  name: pool-manager-config
  namespace: network-pool-manager
data:
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "network_pools"
